import React from 'react';
import SMSFLendingCityPage from '@/components/SMSFLendingCityPage';

export default function SMSFLendingBrisbane() {
  return (
    <SMSFLendingCityPage
      city="Brisbane"
      state="QLD"
      canonical="/services/smsf-lending/cities/brisbane"
      title="SMSF Lending Brisbane | Super Fund Property Loans QLD | Emet Capital"
      description="SMSF lending in Brisbane for trustees purchasing investment property through self-managed super funds with compliant borrowing structures."
      localIntro="SMSF lending for Brisbane trustees who want to acquire investment property through their super fund using a compliant and lender-suitable structure."
      localFocus="Brisbane SMSF lending often involves commercial suites, industrial assets, and selected residential investment property where trustees want long-term property exposure inside super."
      marketOverview="Brisbane’s growth markets can be attractive to SMSF investors, but the quality of the property, the fund’s liquidity, and the legal setup still matter far more than broad market enthusiasm alone."
      timingPressures="In Brisbane, SMSF lending timing is often affected by legal setup, trust coordination, and lender appetite for the specific property type, so early preparation matters."
      suburbCoverage={[{ title: 'CBD and inner commercial precincts', text: 'Commercial strata, office, and smaller investment property in Brisbane CBD and nearby markets may fit certain SMSF strategies.' }, { title: 'TradeCoast and industrial corridors', text: 'Industrial property in logistics-linked areas can suit funds seeking commercial exposure where the asset and strategy fit cleanly.' }, { title: 'Growth-linked suburban investment markets', text: 'Selected residential or mixed investment assets in broader Brisbane growth markets may appeal to trustees with diversified strategies.' }]}
      localUseCases={[{ title: 'Commercial property acquisition in super', text: 'Trustees may use SMSF lending for long-term commercial investment holdings.' }, { title: 'Residential investment via SMSF', text: 'Some SMSFs pursue residential investment assets where the strategy and compliance position are appropriate.' }, { title: 'Retirement diversification into direct property', text: 'Property can support a more diversified SMSF asset mix where trustees want direct exposure.' }, { title: 'Long-term income and asset-control strategy', text: 'Some trustees value the combination of rental income and direct ownership inside the fund structure.' }]}
      scenarios={[{ title: 'Brisbane commercial suite acquisition', scenario: 'An SMSF trustee group wanted to acquire a small office asset without exhausting too much of the fund’s liquid balance.', solution: 'A compliant borrowing structure supported the purchase while preserving stronger liquidity discipline inside the fund.', outcomes: [{ label: 'Property type', value: 'Commercial office suite' }, { label: 'Purchase price', value: '$980K' }, { label: 'Loan structure', value: 'LRBA' }, { label: 'Strategy focus', value: 'Commercial yield' }] }, { title: 'Industrial-property SMSF investment', scenario: 'A fund sought industrial exposure in a Brisbane logistics corridor with a longer-term retirement horizon.', solution: 'The acquisition was structured through an SMSF property loan to preserve compliance and support the broader strategy.', outcomes: [{ label: 'Property type', value: 'Industrial property' }, { label: 'Purchase price', value: '$1.25M' }, { label: 'Loan structure', value: 'SMSF property loan' }, { label: 'Strategy focus', value: 'Long-term yield' }] }, { title: 'Residential SMSF purchase in growth market', scenario: 'A trustee wanted residential property exposure within super but still needed to maintain adequate cash after acquisition.', solution: 'The structure and lender selection focused on maintaining compliance and fund resilience post-settlement.', outcomes: [{ label: 'Property type', value: 'Residential investment' }, { label: 'Purchase price', value: '$740K' }, { label: 'Loan structure', value: 'LRBA' }, { label: 'Strategy focus', value: 'Retirement diversification' }] }]}
      relatedLinks={[{ title: 'SMSF Lending service page', href: '/services/smsf-lending', description: 'National overview of SMSF property lending and LRBA structures.' }, { title: 'Commercial Property Loans Guide', href: '/resources/guides/commercial-property-loans-australia-complete-guide', description: 'Useful if the Brisbane SMSF strategy is focused on commercial property.' }, { title: 'Commercial Property Loan Eligibility', href: '/resources/guides/commercial-property-loan-eligibility-what-you-need-to-qualify', description: 'Helpful for understanding lender expectations around SMSF acquisitions.' }]}
      faqs={[{ question: 'Can an SMSF buy investment property in Brisbane with borrowed funds?', answer: 'Potentially, yes. The property must fit the SMSF strategy and the borrowing arrangement must be structured correctly under a compliant framework.' }, { question: 'Is SMSF lending only for commercial property?', answer: 'No. Depending on lender appetite and compliance, both commercial and residential investment property may be relevant.' }, { question: 'Do lenders care about remaining cash inside the SMSF?', answer: 'Yes. Liquidity after purchase usually matters because the fund still needs to operate prudently after settlement.' }, { question: 'Why is the legal structure so important?', answer: 'Because SMSF borrowing generally uses a limited-recourse borrowing arrangement, and mistakes in setup can create major issues.' }, { question: 'How quickly can Brisbane SMSF lending move?', answer: 'Timing depends on the trust setup, legal coordination, lender fit, and the property type involved.' }]}
    />
  );
}
