import React from 'react';
import SMSFLendingCityPage from '@/components/SMSFLendingCityPage';

export default function SMSFLendingAdelaide() {
  return (
    <SMSFLendingCityPage
      city="Adelaide"
      state="SA"
      canonical="/services/smsf-lending/cities/adelaide"
      title="SMSF Lending Adelaide | Super Fund Property Loans SA | Emet Capital"
      description="SMSF lending in Adelaide for trustees buying investment property through self-managed super funds using compliant borrowing structures."
      localIntro="SMSF lending for Adelaide trustees who want to acquire investment property through their super fund using a compliant and well-structured borrowing arrangement."
      localFocus="Adelaide SMSF lending often involves commercial suites, industrial units, and selected residential investment property where trustees want direct property exposure inside a retirement strategy."
      marketOverview="Adelaide can still offer strong SMSF property opportunities despite being a smaller market, but the legal setup, lender fit, and fund liquidity remain more important than simply liking the asset."
      timingPressures="In Adelaide, SMSF transactions can slow down if the trust setup, legal structure, and lender requirements are not coordinated early enough, so planning matters."
      suburbCoverage={[{ title: 'CBD and inner commercial precincts', text: 'Commercial suites and office assets in Adelaide’s central markets may fit some SMSF commercial-property strategies.' }, { title: 'Wingfield, Regency Park, and industrial corridors', text: 'Industrial units and business property in these areas can suit long-term SMSF commercial holdings where lender appetite aligns.' }, { title: 'Southern and broader suburban investment markets', text: 'Selected suburban residential and mixed investment opportunities may fit some SMSF strategies depending on the fund and lender.' }]}
      localUseCases={[{ title: 'Commercial property acquisition within super', text: 'Trustees may use SMSF lending to buy income-producing commercial property aligned with the fund strategy.' }, { title: 'Residential investment through SMSF', text: 'Some SMSFs pursue residential property as part of a broader retirement diversification plan.' }, { title: 'Long-term retirement diversification', text: 'Property can support a more diversified asset base inside the fund.' }, { title: 'Yield and control-focused strategy', text: 'Some trustees value direct property ownership for longer-term income and retirement planning.' }]}
      scenarios={[{ title: 'Adelaide commercial-suite purchase', scenario: 'An SMSF trustee group wanted a commercial asset inside the fund without draining too much of its cash position.', solution: 'The loan was structured to keep the purchase compliant while preserving better post-settlement flexibility.', outcomes: [{ label: 'Property type', value: 'Commercial suite' }, { label: 'Purchase price', value: '$780K' }, { label: 'Loan structure', value: 'LRBA' }, { label: 'Strategy focus', value: 'Commercial yield' }] }, { title: 'Industrial unit for SMSF investment', scenario: 'A fund wanted industrial property exposure in Adelaide as part of a long-term retirement strategy.', solution: 'The lender fit and structure were chosen to preserve compliance and support the broader SMSF plan.', outcomes: [{ label: 'Property type', value: 'Industrial unit' }, { label: 'Purchase price', value: '$960K' }, { label: 'Loan structure', value: 'SMSF property loan' }, { label: 'Strategy focus', value: 'Yield + diversification' }] }, { title: 'Residential property inside super', scenario: 'A trustee wanted residential investment exposure through the SMSF while keeping enough liquidity inside the fund.', solution: 'The acquisition was structured to preserve both compliance and post-purchase resilience.', outcomes: [{ label: 'Property type', value: 'Residential investment' }, { label: 'Purchase price', value: '$620K' }, { label: 'Loan structure', value: 'LRBA' }, { label: 'Strategy focus', value: 'Retirement diversification' }] }]}
      relatedLinks={[{ title: 'SMSF Lending service page', href: '/services/smsf-lending', description: 'National overview of SMSF lending and LRBA structures.' }, { title: 'Commercial Property Loans Guide', href: '/resources/guides/commercial-property-loans-australia-complete-guide', description: 'Useful if the Adelaide SMSF strategy is focused on commercial property.' }, { title: 'Commercial Property Loan Eligibility', href: '/resources/guides/commercial-property-loan-eligibility-what-you-need-to-qualify', description: 'Helpful for understanding lender expectations around SMSF acquisitions.' }]}
      faqs={[{ question: 'Can an SMSF buy property in Adelaide with borrowed funds?', answer: 'Potentially, yes. The property must fit the SMSF strategy, and the borrowing arrangement must be structured correctly under a compliant framework.' }, { question: 'Is SMSF lending only for large funds?', answer: 'Not necessarily, but lenders do usually care about the fund balance, liquidity, and overall resilience after acquisition.' }, { question: 'Can commercial property work for SMSF lending?', answer: 'Potentially, yes. Commercial property is often relevant where the fund strategy and lender criteria align.' }, { question: 'Why does the trust structure matter so much?', answer: 'Because SMSF borrowing is usually done through a limited-recourse arrangement and the legal setup needs to be right from the beginning.' }, { question: 'How quickly can Adelaide SMSF lending move?', answer: 'Timing depends on trust setup, valuations, legal work, and the lender’s familiarity with the asset and fund structure.' }]}
    />
  );
}
