import React from 'react';
import SMSFLendingCityPage from '@/components/SMSFLendingCityPage';

export default function SMSFLendingPerth() {
  return (
    <SMSFLendingCityPage
      city="Perth"
      state="WA"
      canonical="/services/smsf-lending/cities/perth"
      title="SMSF Lending Perth | Super Fund Property Loans WA | Emet Capital"
      description="SMSF lending in Perth for trustees acquiring investment property through self-managed super funds using compliant borrowing structures."
      localIntro="SMSF lending for Perth trustees who want to use super to acquire investment property through a compliant limited-recourse borrowing structure."
      localFocus="Perth SMSF lending files often involve industrial property, commercial units, and selected residential assets where trustees are looking for long-term property exposure inside a superannuation strategy."
      marketOverview="Perth can offer attractive SMSF property opportunities, especially in industrial and commercial markets, but lender appetite still depends on the property, the fund position, and whether the legal and strategic setup is clean."
      timingPressures="In Perth, SMSF lending timing can be affected by trust setup, adviser coordination, valuation timing, and how comfortable the lender is with the property type and fund profile."
      suburbCoverage={[{ title: 'CBD and central commercial precincts', text: 'Commercial suites and business-focused assets in central Perth may suit SMSF commercial-property strategies.' }, { title: 'Welshpool, Kewdale, and industrial corridors', text: 'Industrial property in these markets can appeal to funds seeking long-term commercial property exposure.' }, { title: 'Canning Vale and wider suburban investment markets', text: 'Selected suburban investment property may fit some residential or mixed retirement strategies where lender appetite and compliance align.' }]}
      localUseCases={[{ title: 'Commercial-property acquisition through SMSF', text: 'Trustees may use SMSF lending to add income-producing commercial property to the fund.' }, { title: 'Residential investment exposure inside super', text: 'Some funds seek residential property exposure through a compliant borrowing structure.' }, { title: 'Long-term retirement diversification', text: 'Property can help diversify SMSF holdings where trustees want direct asset exposure.' }, { title: 'Yield and asset-control strategy', text: 'Some trustees use property inside super as part of a longer-term retirement and income plan.' }]}
      scenarios={[{ title: 'Perth commercial-unit acquisition', scenario: 'A trustee group wanted to buy a small commercial asset through the SMSF while keeping enough liquidity in the fund post-settlement.', solution: 'SMSF lending helped complete the purchase within a compliant structure and a more conservative liquidity position.', outcomes: [{ label: 'Property type', value: 'Commercial unit' }, { label: 'Purchase price', value: '$910K' }, { label: 'Loan structure', value: 'LRBA' }, { label: 'Strategy focus', value: 'Commercial yield' }] }, { title: 'Industrial property SMSF strategy', scenario: 'A fund wanted industrial property exposure in a Perth logistics corridor as part of a longer-term retirement strategy.', solution: 'The structure and lender choice were aligned to preserve compliance and keep the fund’s broader strategy coherent.', outcomes: [{ label: 'Property type', value: 'Industrial property' }, { label: 'Purchase price', value: '$1.18M' }, { label: 'Loan structure', value: 'SMSF property loan' }, { label: 'Strategy focus', value: 'Long-term yield' }] }, { title: 'Residential investment property in super', scenario: 'A trustee wanted a residential investment asset inside the SMSF without overcommitting the fund’s available cash.', solution: 'The lender fit and structure were chosen to support both compliance and post-acquisition flexibility.', outcomes: [{ label: 'Property type', value: 'Residential investment' }, { label: 'Purchase price', value: '$690K' }, { label: 'Loan structure', value: 'LRBA' }, { label: 'Strategy focus', value: 'Retirement diversification' }] }]}
      relatedLinks={[{ title: 'SMSF Lending service page', href: '/services/smsf-lending', description: 'National overview of SMSF property lending and structure requirements.' }, { title: 'Commercial Property Loans Guide', href: '/resources/guides/commercial-property-loans-australia-complete-guide', description: 'Useful if the Perth SMSF strategy centres on commercial property.' }, { title: 'Commercial Property Loan Eligibility', href: '/resources/guides/commercial-property-loan-eligibility-what-you-need-to-qualify', description: 'Helpful for understanding lender requirements for SMSF-backed acquisitions.' }]}
      faqs={[{ question: 'Can an SMSF buy commercial property in Perth with borrowing?', answer: 'Potentially, yes. Many SMSF lending scenarios involve commercial property where the fund strategy, lender fit, and compliance all line up.' }, { question: 'Can residential property also work?', answer: 'Sometimes, yes. It depends on the lender, the trust setup, and whether the acquisition fits the SMSF strategy and rules.' }, { question: 'Do lenders assess the fund’s liquidity?', answer: 'Yes. The fund’s balance, liquidity, and ability to remain sound after purchase usually matter a lot.' }, { question: 'Why is SMSF lending more specialised than a normal loan?', answer: 'Because the structure typically relies on a limited-recourse arrangement and must satisfy strict legal and superannuation requirements.' }, { question: 'How quickly can Perth SMSF lending move?', answer: 'It depends on the legal setup, valuation timing, lender fit, and the property involved. Clean preparation helps materially.' }]}
    />
  );
}
