import React from 'react';
import TradeFinanceCityPage from '@/components/TradeFinanceCityPage';

export default function TradeFinancePerth() {
  return (
    <TradeFinanceCityPage
      city="Perth"
      state="WA"
      canonical="/services/trade-finance/cities/perth"
      title="Trade Finance Perth | Import & Export Funding WA | Emet Capital"
      description="Trade finance in Perth for importers, exporters, distributors, and trade businesses managing supplier timing, stock cycles, and export receivables."
      localIntro="Trade finance for Perth businesses that need import, export, and supply-chain funding aligned to real trading cycles and shipment timing."
      localFocus="Perth trade-finance scenarios often involve supplier funding, export receivables, stock carrying, and timing pressure linked to logistics and project-based supply chains."
      marketOverview="Perth businesses can face longer supply chains, project-linked trade cycles, and larger timing gaps between supplier payment and customer collection. That makes the right trade-finance structure especially valuable where cash flow is otherwise being stretched by the trade cycle itself."
      timingPressures="In Perth, trade-finance pressure commonly appears when suppliers must be paid before stock turns, export customers pay later than the operating cycle allows, or shipment timing creates short-term capital strain."
      suburbCoverage={[{ title: 'CBD and central commercial precincts', text: 'Perth CBD and central business areas often generate trade-finance needs for commercial trading and service-distribution businesses.' }, { title: 'Kewdale, Welshpool, and logistics corridors', text: 'These precincts frequently produce supplier-timing, stock, and transport-led trade-finance scenarios.' }, { title: 'Canning Vale, Malaga, and outer industrial markets', text: 'Industrial and wholesale businesses here often need funding aligned to inventory, logistics, and receivable cycles.' }]}
      localUseCases={[{ title: 'Import and supplier payment timing', text: 'Trade finance may help Perth businesses fund supplier obligations while goods are still in transit or not yet sold.' }, { title: 'Export receivables and customer timing', text: 'Exporters may need support between shipment and final payment receipt.' }, { title: 'Stock carrying and distribution cycles', text: 'Businesses may need funding aligned to inventory and customer terms rather than a rigid generic loan product.' }, { title: 'Project-linked trade support', text: 'Some operators use trade finance to support supply-chain timing linked to larger customer or project cycles.' }]}
      scenarios={[{ title: 'Kewdale supplier timing facility', scenario: 'A distributor needed to pay overseas suppliers before inventory had been sold through local customer channels.', solution: 'Trade finance supported the supplier cycle and preserved broader business liquidity.', outcomes: [{ label: 'Facility size', value: '$880K' }, { label: 'Primary need', value: 'Import funding' }, { label: 'Industry', value: 'Distribution' }, { label: 'Expected exit', value: 'Stock turn + receipts' }] }, { title: 'Perth export receivable bridge', scenario: 'An exporter needed support between shipment and customer payment to keep operations stable.', solution: 'A receivables-based trade structure smoothed the gap and reduced pressure on the wider business.', outcomes: [{ label: 'Facility size', value: '$570K' }, { label: 'Primary need', value: 'Export receivables' }, { label: 'Industry', value: 'Export/trade' }, { label: 'Expected exit', value: 'Customer collections' }] }, { title: 'Canning Vale stock-cycle support', scenario: 'A wholesale operator needed room to hold more stock while waiting for incoming payments.', solution: 'Trade finance helped align inventory and debtor timing more sensibly.', outcomes: [{ label: 'Facility size', value: '$490K' }, { label: 'Primary need', value: 'Inventory cycle support' }, { label: 'Industry', value: 'Wholesale' }, { label: 'Expected exit', value: 'Inventory turn + collections' }] }]}
      relatedLinks={[{ title: 'Trade Finance service page', href: '/services/trade-finance', description: 'National overview of trade-finance structures and lender fit.' }, { title: 'Trade Finance in Australia guide', href: '/resources/guides/trade-finance-in-australia-how-it-helps-businesses-manage-imports', description: 'Guide to import and export funding strategies.' }, { title: 'Debtor Finance & Supply Chain Finance', href: '/resources/guides/debtor-finance-supply-chain-finance-australia', description: 'Useful if the Perth issue is tied strongly to debtors or supplier-chain timing.' }]}
      faqs={[{ question: 'When might a Perth business use trade finance?', answer: 'Usually when it needs support with supplier payments, imports, exports, inventory timing, or debtor cycles tied to trade.' }, { question: 'Can trade finance help with longer supplier cycles?', answer: 'Potentially, yes. Some facilities are specifically useful where goods or supply-chain timing create a lag between payment and cash return.' }, { question: 'Do lenders focus on the goods and trade cycle?', answer: 'Yes. Goods profile, margins, counterparties, and timing across the trade cycle all usually matter.' }, { question: 'Is trade finance always tied to international trade?', answer: 'Not always, but many structures are especially relevant where imports, exports, and supply chains create timing pressure.' }, { question: 'How quickly can Perth trade finance move?', answer: 'It depends on the lender and structure, but cleanly prepared trade files can move more efficiently than people expect.' }]}
    />
  );
}
