// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bgkwqalttxruzgslheov.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJna3dxYWx0dHhydXpnc2xoZW92Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxMTE1ODgsImV4cCI6MjA3MTY4NzU4OH0.-C5UpdC4TWVRcPBxJ4WV1IcbcuBugN-O9_LPgqsIYpI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});